FROM node:16-alpine

RUN yarn set version berry

WORKDIR /app

COPY ./../package.json .
COPY ./../.yarnrc.yml .
COPY ./../lerna.json .
COPY ./../yarn.lock .
COPY ./../client ./client

RUN yarn install
RUN yarn build:client

EXPOSE 8080

CMD ["node", "dist/ssr"]

